name: main

on:
  [ push, pull_request ]
    
jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v6
        name: setup Python
        with:
          python-version: '3.12'
      - name: Install pywis-topics
        run: |
          pip3 install -e .
          pywis-topics --version
          pywis-topics bundle sync
      - name: run tests
        run: python3 tests/run_tests.py
